- name: 3-dns-server
  hosts: dns

  tasks: 
  - name: check if master config exists
    stat:
      path: /etc/bind/named.conf.master
    register: master_file

  - name: check if slave_file config exists
    stat:
      path: /etc/bind/named.conf.slave
    register: slave_file

  - name: send master files
    copy:
      src: '/data/ansible/linux/{{item}}'
      dest: '/etc/bind'
      owner: bind
      group: bind
      mode: 0777
    loop:
    - named.conf.options
    - named.conf
    - 0.22.10.db
    - applix.com.lan.
    - named.conf.master
    when: (groups['dns'][0] == inventory_hostname) and (not master_file.stat.exists)
  - name: append to the bind options for slave
    shell: |
      echo "include \"/etc/bind/named.conf.slave\";" >> /etc/bind/named.conf
    when: (groups['dns'][0] != inventory_hostname) and (not slave_file.stat.exists)

  - name: send slave files
    copy:
      src: '/data/ansible/linux/{{item}}'
      dest: '/etc/bind'
      owner: bind
      group: bind
      mode: 0777
    loop:
    - named.conf.slave
    when: (groups['dns'][0] != inventory_hostname) and (not slave_file.stat.exists)

  - name: update all bind configuration
    shell: |
      systemctl restart named
    when: ((groups['dns'][0] == inventory_hostname) and (not master_file.stat.exists)) or (groups['dns'][0] != inventory_hostname) and (not slave_file.stat.exists)
    
  
